feat(cicd): workflow 재 설정

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -10,38 +10,45 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v2
+      - uses: actions/checkout@v2
 
-      - name: Set up Python
-        uses: actions/setup-python@v2
+      - name: Set up JDK 17
+        uses: actions/setup-java@v2
         with:
-          python-version: '3.8'
+          java-version: '17'
+          distribution: 'temurin'
 
-      - name: Execute version increment script
-        id: increment_version
+      - name: Build with Gradle
         run: |
-          python3 increment_version.py
-        env:
-          CURRENT_VERSION: ${{ steps.set_version.outputs.version }}
+          ./gradlew assemble --no-daemon
+          ./gradlew --stop
 
       - name: Build Docker image
         env:
           DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
           DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
-          IMAGE_TAG: ${{ steps.increment_version.outputs.new_version }}
+          IMAGE_TAG: ${{ github.run_number }}
         run: |
           echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
           docker build -t food-delivery .
           docker tag food-delivery:latest hyuuny/food-delivery:${IMAGE_TAG}
-          docker push food-delivery:${IMAGE_TAG}
+          docker push hyuuny/food-delivery:${IMAGE_TAG}
 
       - name: Run Tests
         run: |
-          # Add commands to run tests here
+          ./gradlew test --no-daemon
+          ./gradlew --stop
+
+      - name: Check Test Results
+        run: |
+          TEST_EXIT_CODE=$?
+          if [ $TEST_EXIT_CODE -ne 0 ]; then
+            echo "Tests failed. Exiting with code $TEST_EXIT_CODE"
+            exit $TEST_EXIT_CODE
+          fi
 
       - name: Archive Build Artifacts
         uses: actions/upload-artifact@v2
         with:
           name: build-artifacts
-          path: path/to/artifacts
+          path: build/libs/*.jar
